spring:
  datasource:
    url: jdbc:postgresql://localhost:54320/test
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    baseline-on-migrate: true
  kafka:
    consumer:
      group-id: group-1
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
jwt:
  token:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

server:
  servlet:
    context-path: /api/v1

schedule:
  announcement:
    expire:
      delay: 30000